### ISSUE TITLE
Builds of public site development branches cause error

### ISSUE THREAD

**Issue by helrond** [RockefellerArchiveCenter/docs-build#202]
## Describe the bug
Because we don't have a public development site (and therefore do not have a public development S3 bucket) builds in the development branch of public repositories raise an exception and do not complete.

## To reproduce
Best way to look at this is to review logs in Cloudwatch.

## Expected behavior
Public development sites should be built and pushed to the internal development site only.

## Impact on your work
The dev site is a core component of our docs workflow, so it needs to work as expected.

## Additional context
This can probably be fixed by either raising an handling a custom exception or adding some conditionals in the run method which prevent public development build attempts.

**Comment by HaSistrunk** [comment]
Closed with PR #203
