### ISSUE TITLE
Docker for local development isn't serving site locally as expected

### ISSUE THREAD

**Issue by HaSistrunk** [RockefellerArchiveCenter/docs-build#210]
## Describe the bug
If I follow the quick start guide and run `docker-compose build` and `docker-compose up`, it doesn't run the site locally as expected.

## To reproduce
1. Clone repo
2. Run 'docker-compose build'. Writes an image.
3. Run `docker-compose up`. 
4. The terminal just shows:
```
Container docs-build-docs-build-1  Created 0.0s
Attaching to docs-build-docs-build-1
docs-build-docs-build-1 exited with code 0
```

## Expected behavior
Docker would spin up the public site and be available at `http://localhost:4000`

## Impact on your work
We need to be able to see the site for local development

**Comment by HaSistrunk** [comment]
Is this related to this comment in `entrypoint.sh`? https://github.com/RockefellerArchiveCenter/docs-build/blob/40d6b6202efcc97daa78dfd1db6dc120807e5e7d/entrypoint.sh#L3

**Comment by helrond** [comment]
@HaSistrunk yes.
