### ISSUE TITLE
Table of contents does not scroll when it is too large to fit on one page

### ISSUE THREAD

**Issue by HaSistrunk** [RockefellerArchiveCenter/docs-build#42]
See http://docs.rockarch.org/processing_manual/processing for an example. The table of contents won't scroll to the bottom until you scroll to the bottom of the main page.

**Comment by kemartin2015** [comment]
https://projects.jga.me/toc/#toc7

From the toc.js website - Part of the future development goals: "Figure out how to handle headlines on bottom of page"

**Comment by kemartin2015** [comment]
Side navigation - needs headers turned into lists/list items; each list item needs to be a link - currently, toc.js does everything
