### ISSUE TITLE
Review text color contrast

### ISSUE THREAD

**Issue by HaSistrunk** [RockefellerArchiveCenter/docs-build#56]
WCAG 2.0 level AA requires a contrast ratio of at least 4.5:1 for normal text and 3:1 for large text. Level AAA requires a contrast ratio of at least 7:1 for normal text and 4.5:1 for large text
[WebAIM Color Contrast Checker](https://webaim.org/resources/contrastchecker/).

**Comment by daremiyo** [comment]
custom css for classes on buttons and badges?

**Comment by HaSistrunk** [comment]
Tested, and the contrast is good on the development branch.
