### ISSUE TITLE
Development site is not updating when changes are made

### ISSUE THREAD

**Issue by HaSistrunk** [RockefellerArchiveCenter/docs-build#79]
When changes are made to the development branch of a repo, they should update automatically on the site. This is not currently happening. Running `update.py` manually sometimes triggers the build process and update, but not consistently.

**Comment by helrond** [comment]
Have added print statements which show up in `/home/docs/docs_build/log.txt` so we can troubleshoot a bit more effectively.

**Comment by helrond** [comment]
@HaSistrunk is this still happening?

**Comment by HaSistrunk** [comment]
This is still happening, but not consistently. I think this issue is related to private repos being cloned with https instead of ssh, because it was working, and then stopped working when a recent repo was cloned to the server with https and then the repo was switched to be private.

**Comment by HaSistrunk** [comment]
Yes, so I think that was the issue. I fixed the recent repo and it is now updating automatically.
