### ISSUE TITLE
Better user feedback for category filters

### ISSUE THREAD

**Issue by helrond** [RockefellerArchiveCenter/docs-build#99]
## Is your feature request related to a problem? Please describe.
Category filtering is still non-obvious. When you click on a category filter, particularly if it doesn't hide any of the cards in the top row of the site, it's not at all clear that anything happened.

## Describe the solution you'd like
We need to provide better feedback to users to let them know that a) something happened and b) what exactly that something was. I propose two things:
1. Some sort of animation styling that indicates that the system is doing something. This could be an overlay, a fade out/fade in, etc.
2. When a button has been clicked, some visual indication that this filter is active, either text that says "filtered by foo" or some styling on the button that indicates that value is active.

I also think we should add some URL parameters when these buttons are clicked so that people can reference particular categories of documentation.

## Additional context
I can probably handle the implementation of this pretty easily, but I'd like to hear if the above sounds right, and if you have any guidance on which path to take.

**Comment by helrond** [comment]
@kemartin2015 can you drop a screenshot in here so we have it to reference?

**Comment by kemartin2015** [comment]
![Filter_By](https://user-images.githubusercontent.com/29953004/67976432-6fea7200-fbec-11e9-9c37-9ba5199d4701.png)
